version: "3.8"

services:
  django:
    container_name: backend
    build:
      context: ./backend
    env_file:
      - ./backend/.env
    ports:
      - 8000:8000
    volumes:
      - ./backend:/backend