# Generated by Django 4.2.2 on 2023-06-08 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClimateData',
            fields=[
                ('year', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('january', models.IntegerField(default=0, null=True)),
                ('february', models.IntegerField(default=0, null=True)),
                ('march', models.IntegerField(default=0, null=True)),
                ('april', models.IntegerField(default=0, null=True)),
                ('may', models.IntegerField(default=0, null=True)),
                ('june', models.IntegerField(default=0, null=True)),
                ('july', models.IntegerField(default=0, null=True)),
                ('august', models.IntegerField(default=0, null=True)),
                ('september', models.IntegerField(default=0, null=True)),
                ('october', models.IntegerField(default=0, null=True)),
                ('november', models.IntegerField(default=0, null=True)),
                ('december', models.IntegerField(default=0, null=True)),
                ('winter', models.IntegerField(default=0, null=True)),
                ('summer', models.IntegerField(default=0, null=True)),
                ('autmn', models.IntegerField(default=0, null=True)),
                ('spring', models.IntegerField(default=0, null=True)),
            ],
        ),
    ]
