# Generated by Django 4.2.2 on 2023-06-08 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_scrapper', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='climatedata',
            old_name='april',
            new_name='Quarter1',
        ),
        migrations.RenameField(
            model_name='climatedata',
            old_name='august',
            new_name='Quarter2',
        ),
        migrations.RenameField(
            model_name='climatedata',
            old_name='december',
            new_name='Quarter3',
        ),
        migrations.RenameField(
            model_name='climatedata',
            old_name='february',
            new_name='Quarter4',
        ),
        migrations.RemoveField(
            model_name='climatedata',
            name='january',
        ),
        migrations.RemoveField(
            model_name='climatedata',
            name='july',
        ),
        migrations.RemoveField(
            model_name='climatedata',
            name='june',
        ),
        migrations.RemoveField(
            model_name='climatedata',
            name='march',
        ),
        migrations.RemoveField(
            model_name='climatedata',
            name='may',
        ),
        migrations.RemoveField(
            model_name='climatedata',
            name='november',
        ),
        migrations.RemoveField(
            model_name='climatedata',
            name='october',
        ),
        migrations.RemoveField(
            model_name='climatedata',
            name='september',
        ),
    ]
