# Generated by Django 4.2.2 on 2023-06-08 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_scrapper', '0002_rename_april_climatedata_quarter1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='climatedata',
            name='Quarter1',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='climatedata',
            name='Quarter2',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='climatedata',
            name='Quarter3',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='climatedata',
            name='Quarter4',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='climatedata',
            name='autmn',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='climatedata',
            name='spring',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='climatedata',
            name='summer',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='climatedata',
            name='winter',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
