# Generated by Django 4.2.2 on 2023-06-08 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_scrapper', '0003_alter_climatedata_quarter1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=50)),
                ('parameter', models.CharField(max_length=50)),
                ('year', models.IntegerField(default=0)),
                ('january', models.IntegerField(default=0, null=True)),
                ('february', models.IntegerField(default=0, null=True)),
                ('march', models.IntegerField(default=0, null=True)),
                ('april', models.IntegerField(default=0, null=True)),
                ('may', models.IntegerField(default=0, null=True)),
                ('june', models.IntegerField(default=0, null=True)),
                ('july', models.IntegerField(default=0, null=True)),
                ('august', models.IntegerField(default=0, null=True)),
                ('september', models.IntegerField(default=0, null=True)),
                ('october', models.IntegerField(default=0, null=True)),
                ('november', models.IntegerField(default=0, null=True)),
                ('december', models.IntegerField(default=0, null=True)),
                ('winter', models.IntegerField(default=0, null=True)),
                ('summer', models.IntegerField(default=0, null=True)),
                ('autmn', models.IntegerField(default=0, null=True)),
                ('spring', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ClimateData',
        ),
    ]
