# Generated by Django 4.2.2 on 2023-08-03 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SeasonsalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('value', models.FloatField(null=True)),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather_api.parameter')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather_api.region')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather_api.season')),
            ],
            options={
                'verbose_name_plural': 'Seasonal Data',
                'unique_together': {('region', 'parameter', 'year', 'season')},
            },
        ),
        migrations.CreateModel(
            name='MonthlyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('value', models.FloatField(null=True)),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather_api.month')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather_api.parameter')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather_api.region')),
            ],
            options={
                'verbose_name_plural': 'Monthly Data',
                'unique_together': {('region', 'parameter', 'year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='AnnualData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('annual_data', models.FloatField(null=True)),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather_api.parameter')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather_api.region')),
            ],
            options={
                'verbose_name_plural': 'Annual Data',
                'unique_together': {('region', 'parameter', 'year')},
            },
        ),
    ]
