# Generated by Django 4.2.2 on 2023-06-09 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherdata',
            name='annual',
            field=models.FloatField(default=0, null=True),
        ),
    ]
