# Generated by Django 4.2.2 on 2023-06-09 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=50)),
                ('parameter', models.CharField(max_length=50)),
                ('year', models.IntegerField(default=0)),
                ('jan', models.FloatField(default=0, null=True)),
                ('feb', models.FloatField(default=0, null=True)),
                ('mar', models.FloatField(default=0, null=True)),
                ('apr', models.FloatField(default=0, null=True)),
                ('may', models.FloatField(default=0, null=True)),
                ('jun', models.FloatField(default=0, null=True)),
                ('jul', models.FloatField(default=0, null=True)),
                ('aug', models.FloatField(default=0, null=True)),
                ('sep', models.FloatField(default=0, null=True)),
                ('oct', models.FloatField(default=0, null=True)),
                ('nov', models.FloatField(default=0, null=True)),
                ('dec', models.FloatField(default=0, null=True)),
                ('winter', models.FloatField(default=0, null=True)),
                ('summer', models.FloatField(default=0, null=True)),
                ('autmn', models.FloatField(default=0, null=True)),
                ('spring', models.FloatField(default=0, null=True)),
            ],
            options={
                'unique_together': {('region', 'parameter', 'year')},
            },
        ),
    ]
