# Generated by Django 4.2.2 on 2023-06-24 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("weather_api", "0002_weatherdata_annual"),
    ]

    operations = [
        migrations.CreateModel(
            name="MonthlyData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month_name", models.CharField(max_length=50, unique=True)),
                ("monthly_data", models.FloatField(null=True)),
                ("annual_data", models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Parameter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("parameter_name", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="SeasonsalData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("season_name", models.CharField(max_length=20, unique=True)),
                ("seasonal_data", models.FloatField(null=True)),
                (
                    "parameter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="weather_api.parameter",
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="weather_api.region",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Year",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year_name", models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name="WeatherData",
        ),
        migrations.AddField(
            model_name="seasonsaldata",
            name="year",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="weather_api.year"
            ),
        ),
        migrations.AddField(
            model_name="monthlydata",
            name="parameter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="weather_api.parameter"
            ),
        ),
        migrations.AddField(
            model_name="monthlydata",
            name="region",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="weather_api.region"
            ),
        ),
        migrations.AddField(
            model_name="monthlydata",
            name="year",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="weather_api.year"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="seasonsaldata",
            unique_together={("region", "parameter", "year", "season_name")},
        ),
        migrations.AlterUniqueTogether(
            name="monthlydata",
            unique_together={("region", "parameter", "year", "month_name")},
        ),
    ]
