# Generated by Django 4.2.2 on 2023-06-25 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "weather_api",
            "0003_monthlydata_parameter_region_seasonsaldata_year_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="monthlydata",
            name="year",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="seasonsaldata",
            name="year",
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name="Year",
        ),
    ]
