# Generated by Django 4.2.2 on 2023-06-25 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "weather_api",
            "0004_alter_monthlydata_year_alter_seasonsaldata_year_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="region",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
