# Generated by Django 4.2.2 on 2023-06-25 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("weather_api", "0005_alter_region_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="monthlydata",
            name="month_name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="seasonsaldata",
            name="season_name",
            field=models.CharField(max_length=20),
        ),
    ]
