# Generated by Django 4.2.2 on 2023-06-26 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("weather_api", "0006_alter_monthlydata_month_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnnualData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField()),
                ("annual_data", models.FloatField(null=True)),
                (
                    "parameter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="weather_api.parameter",
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="weather_api.region",
                    ),
                ),
            ],
            options={
                "unique_together": {("region", "parameter", "year")},
            },
        ),
    ]
