# Generated by Django 4.2.2 on 2023-06-28 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("weather_api", "0007_annualdata"),
    ]

    operations = [
        migrations.CreateModel(
            name="Month",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Season",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="monthlydata",
            name="annual_data",
        ),
        migrations.AlterField(
            model_name="monthlydata",
            name="month_name",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="weather_api.month"
            ),
        ),
        migrations.AlterField(
            model_name="seasonsaldata",
            name="season_name",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="weather_api.season"
            ),
        ),
    ]
