# Generated by Django 4.2.2 on 2023-06-28 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("weather_api", "0008_month_season_remove_monthlydata_annual_data_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="monthlydata",
            old_name="month_name",
            new_name="month",
        ),
        migrations.RenameField(
            model_name="monthlydata",
            old_name="monthly_data",
            new_name="value",
        ),
        migrations.RenameField(
            model_name="seasonsaldata",
            old_name="season_name",
            new_name="season",
        ),
        migrations.RenameField(
            model_name="seasonsaldata",
            old_name="seasonal_data",
            new_name="value",
        ),
        migrations.AlterUniqueTogether(
            name="monthlydata",
            unique_together={("region", "parameter", "year", "month")},
        ),
        migrations.AlterUniqueTogether(
            name="seasonsaldata",
            unique_together={("region", "parameter", "year", "season")},
        ),
    ]
