# Generated by Django 4.2.2 on 2023-06-28 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("weather_api", "0009_rename_month_name_monthlydata_month_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="parameter",
            old_name="parameter_name",
            new_name="name",
        ),
    ]
